### ISSUE TITLE
Can't get it to run

### ISSUE THREAD

**Issue by simonmcnair** [11notes/docker-adguard#1]
Hi,
Firstly thanks for putting the effort in to put this together.  I came after seeing your posts on Reddit, I appreciate your wisdom.

I can't get the container to work though.  It's probably my fault.  I assume it's perhaps a requirement to root docker rootless but I don't know.  Also I am unsure of how to make it rootless, if I should, and what other docker images it would potentially break.

The error I get is:

2024/09/24 11:38:23.512378 [info] AdGuard Home, version v0.107.43
2024/09/24 11:38:23.512419 [info] This is the first time AdGuard Home is launched
2024/09/24 11:38:23.512423 [info] Checking if AdGuard Home has necessary permissions
2024/09/24 11:38:23.512427 [fatal] This is the first launch of AdGuard Home. You must run it as Administrator.

I tried enable privileged ports as I assume port 53 couldn't be bound.  But I couldn't get it to work, same error.

I have gone to adguard/adguard and that works.

Might also be worth stating what the advantage of your image is over the original.

Thanks for your efforts, I hope you don't take offence at the issue I have raised.

**Comment by 11notes** [comment]
Try this compose:
```
services:
  adguard:
    image: "11notes/adguard:0.107.52"
    container_name: "adguard"
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "etc:/adguard/etc"
      - "var:/adguard/var"
	  ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8443:8443/tcp"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=53
    restart: always
volumes:
  etc:
  var:
```
