### ISSUE TITLE
Getting this error upon startup: Couldn't write PID to file

### ISSUE THREAD

**Issue by ovizii** [11notes/docker-adguard#3]
I'm trying to switch from the official image to yours, so I have compared compose files and adapted my config file but for some reason I get this error. Seems unrelated to anything I have done as my volume mapping does not touch `/adguard/run` 

excerpt:
```
    volumes:
      - ./work:/adguard/var
      - ./confdir:/adguard/etc
```

```
adguardhome | 2025/04/19 18:01:02.155148 [info] starting plain server server=plain addr=0.0.0.0:3000
adguardhome | 2025/04/19 18:01:23.453986 [info] received signal signal=terminated
adguardhome | 2025/04/19 18:01:23.454025 [info] stopping AdGuard Home
adguardhome | 2025/04/19 18:01:23.454042 [info] webapi: stopping http server
adguardhome | 2025/04/19 18:01:23.454219 [info] webapi: stopped http server
adguardhome | 2025/04/19 18:01:23.457789 [info] stopped
adguardhome | 2025/04/19 18:01:24.758043 [info] AdGuard Home, version 0.107.59
adguardhome | 2025/04/19 18:01:24.764496 [info] tls: using default ciphers
adguardhome | 2025/04/19 18:01:24.766244 [error] Couldn't write PID to file /adguard/run/adguard.pid: open /adguard/run/adguard.pid: read-only file system
adguardhome | 2025/04/19 18:01:24.797533 [info] Initializing auth module: /adguard/var/data/sessions.db
```

**Comment by ovizii** [comment]
Forgot to mention I use this image:

```
  adguardhome:
    image: 11notes/adguard:stable
```

**Comment by 11notes** [comment]
I'm terribly sorry, I forgot to update the compose with the tmpfs example for the PID. I will add it later when I add armv7 but here is the version:

```yml
name: "adguard"
services:
  adguard:
    image: "11notes/adguard:0.107.59"
    read_only: true
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "etc:/adguard/etc"
      - "var:/adguard/var"
    tmpfs:
      # tmpfs volume because of read_only: true
      - "/adguard/run:uid=1000,gid=1000"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "3000:3000/tcp"
    networks:
      frontend:
    sysctls:
      # allow rootless container to access ports < 1024
      net.ipv4.ip_unprivileged_port_start: 53
    restart: "always"

volumes:
  etc:
  var:

networks:
  frontend:
```
