### ISSUE TITLE
Afterer switching from the official image to this one, my adguardhoem is stuck in a permanent restart loop

### ISSUE THREAD

**Issue by ovizii** [11notes/docker-adguard#4]
**I can't spot the problem, would love to get any tips if possible.**

Container with this image, keeps looping like this:

```
docker compose logs  -f
adguardhome  | 2025/04/19 23:07:31.701386 [info] AdGuard Home, version 0.107.59
adguardhome  | 2025/04/19 23:07:31.707189 [info] tls: using default ciphers
adguardhome  | 2025/04/19 23:07:31.730219 [info] Initializing auth module: /adguard/var/data/sessions.db
adguardhome  | 2025/04/19 23:07:31.734122 [info] auth: initialized.  users:1  sessions:1
adguardhome  | 2025/04/19 23:07:31.734178 [info] webapi: initializing
adguardhome  | 2025/04/19 23:07:33.869194 [info] dnsproxy: upstream mode is set mode=parallel
adguardhome  | 2025/04/19 23:07:33.869234 [info] dnsproxy: cache enabled size=4096
adguardhome  | 2025/04/19 23:07:33.869252 [info] dnsproxy: max goroutines is set count=1024
adguardhome  | 2025/04/19 23:07:33.869291 [info] dnsproxy: ratelimit is enabled rps=120 ipv4_subnet_mask_len=24 ipv6_subnet_mask_len=56
adguardhome  | 2025/04/19 23:07:33.869303 [info] dnsproxy: server will refuse requests of type any
adguardhome  | 2025/04/19 23:07:33.869319 [info] dnsproxy: upstream mode is set mode=parallel
adguardhome  | 2025/04/19 23:07:33.869335 [info] dnsproxy: cache enabled size=1073741824
adguardhome  | 2025/04/19 23:07:33.869348 [info] dnsproxy: max goroutines is set count=1024
adguardhome  | 2025/04/19 23:07:33.870244 [info] addrproc: processing addresses
adguardhome  | 2025/04/19 23:07:33.870326 [info] webapi: AdGuard Home is available at the following addresses:
adguardhome  | 2025/04/19 23:07:33.870658 [info] go to http://127.0.0.1:3000
adguardhome  | 2025/04/19 23:07:33.870697 [info] go to http://[::1]:3000
adguardhome  | 2025/04/19 23:07:33.870707 [info] go to http://172.16.1.2:3000
adguardhome  | 2025/04/19 23:07:33.870714 [info] go to http://192.168.191.18:3000
adguardhome  | 2025/04/19 23:07:33.870764 [info] starting plain server server=plain addr=0.0.0.0:3000
adguardhome  | 2025/04/19 23:07:48.652237 [info] received signal signal=terminated
adguardhome  | 2025/04/19 23:07:48.652264 [info] stopping AdGuard Home
adguardhome  | 2025/04/19 23:07:48.652280 [info] webapi: stopping http server
adguardhome  | 2025/04/19 23:07:48.652412 [info] webapi: stopped http server
adguardhome  | 2025/04/19 23:07:48.652594 [info] stopped
adguardhome  | 2025/04/19 23:07:49.412136 [info] AdGuard Home, version 0.107.59
adguardhome  | 2025/04/19 23:07:49.418046 [info] tls: using default ciphers
adguardhome  | 2025/04/19 23:07:49.427529 [info] Initializing auth module: /adguard/var/data/sessions.db
adguardhome  | 2025/04/19 23:07:49.427646 [info] auth: initialized.  users:1  sessions:1
adguardhome  | 2025/04/19 23:07:49.427728 [info] webapi: initializing
adguardhome  | 2025/04/19 23:07:51.118836 [info] dnsproxy: upstream mode is set mode=parallel
adguardhome  | 2025/04/19 23:07:51.118864 [info] dnsproxy: cache enabled size=4096
adguardhome  | 2025/04/19 23:07:51.118880 [info] dnsproxy: max goroutines is set count=1024
adguardhome  | 2025/04/19 23:07:51.118932 [info] dnsproxy: ratelimit is enabled rps=120 ipv4_subnet_mask_len=24 ipv6_subnet_mask_len=56
adguardhome  | 2025/04/19 23:07:51.118945 [info] dnsproxy: server will refuse requests of type any
adguardhome  | 2025/04/19 23:07:51.118958 [info] dnsproxy: upstream mode is set mode=parallel
adguardhome  | 2025/04/19 23:07:51.118969 [info] dnsproxy: cache enabled size=1073741824
adguardhome  | 2025/04/19 23:07:51.118982 [info] dnsproxy: max goroutines is set count=1024
adguardhome  | 2025/04/19 23:07:51.119708 [info] addrproc: processing addresses
adguardhome  | 2025/04/19 23:07:51.119735 [info] webapi: AdGuard Home is available at the following addresses:
adguardhome  | 2025/04/19 23:07:51.120012 [info] go to http://127.0.0.1:3000
adguardhome  | 2025/04/19 23:07:51.120022 [info] go to http://[::1]:3000
adguardhome  | 2025/04/19 23:07:51.120028 [info] go to http://172.16.1.2:3000
adguardhome  | 2025/04/19 23:07:51.120034 [info] go to http://192.168.191.18:3000
adguardhome  | 2025/04/19 23:07:51.120073 [info] starting plain server server=plain addr=0.0.0.0:3000
adguardhome  | 2025/04/19 23:08:09.311178 [info] received signal signal=terminated
adguardhome  | 2025/04/19 23:08:09.311199 [info] stopping AdGuard Home
adguardhome  | 2025/04/19 23:08:09.311215 [info] webapi: stopping http server
adguardhome  | 2025/04/19 23:08:09.311337 [info] webapi: stopped http server
adguardhome  | 2025/04/19 23:08:09.311588 [info] stopped
adguardhome exited with code 0

```

Container with original image, starts like this:

```
docker compose logs  -f
adguardhome  | 2025/04/19 20:08:44.595783 [info] AdGuard Home, version v0.107.59
adguardhome  | 2025/04/19 20:08:44.603626 [info] tls: using default ciphers
adguardhome  | 2025/04/19 20:08:44.616654 [info] Initializing auth module: /opt/adguardhome/work/data/sessions.db
adguardhome  | 2025/04/19 20:08:44.617455 [info] auth: initialized.  users:1  sessions:1
adguardhome  | 2025/04/19 20:08:44.617734 [info] webapi: initializing
adguardhome  | 2025/04/19 20:08:46.434872 [info] dnsproxy: upstream mode is set mode=parallel
adguardhome  | 2025/04/19 20:08:46.434952 [info] dnsproxy: cache enabled size=4096
adguardhome  | 2025/04/19 20:08:46.435047 [info] dnsproxy: ratelimit is enabled rps=120 ipv4_subnet_mask_len=24 ipv6_subnet_mask_len=56
adguardhome  | 2025/04/19 20:08:46.435075 [info] dnsproxy: server will refuse requests of type any
adguardhome  | 2025/04/19 20:08:46.435087 [info] dnsproxy: upstream mode is set mode=parallel
adguardhome  | 2025/04/19 20:08:46.435099 [info] dnsproxy: cache enabled size=4194304
adguardhome  | 2025/04/19 20:08:46.436230 [info] addrproc: processing addresses
adguardhome  | 2025/04/19 20:08:46.436373 [info] webapi: AdGuard Home is available at the following addresses:
adguardhome  | 2025/04/19 20:08:46.436779 [info] go to http://127.0.0.1:80
adguardhome  | 2025/04/19 20:08:46.436792 [info] go to http://[::1]:80
adguardhome  | 2025/04/19 20:08:46.436798 [info] go to http://172.16.1.2:80
adguardhome  | 2025/04/19 20:08:46.436803 [info] go to http://192.168.191.18:80
adguardhome  | 2025/04/19 20:08:46.436910 [info] starting plain server server=plain addr=0.0.0.0:80
adguardhome  | 2025/04/19 20:09:11.972364 [info] dnsproxy: starting dns proxy server
adguardhome  | 2025/04/19 20:09:11.972905 [info] dnsproxy: creating udp server socket addr=0.0.0.0:53
adguardhome  | 2025/04/19 20:09:11.973772 [info] dnsproxy: listening to udp addr=[::]:53
adguardhome  | 2025/04/19 20:09:11.974073 [info] dnsproxy: creating tcp server socket addr=0.0.0.0:53
adguardhome  | 2025/04/19 20:09:11.974182 [info] dnsproxy: listening to tcp addr=[::]:53
adguardhome  | 2025/04/19 20:09:11.974549 [info] dnsproxy: entering udp listener loop addr=[::]:53
adguardhome  | 2025/04/19 20:09:11.975118 [info] dnsproxy: entering listener loop proto=tcp addr=[::]:53

```

Here is my compose file:

```
services:
  adguardhome:
    image: 11notes/adguard:stable
    container_name: adguardhome
    hostname: adguardhome
    restart: "no"
    read_only: true
    tmpfs:
      - "/adguard/run:uid=1000,gid=1000" #tmpfs volume because of read_only: true
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 53
    ports:
      - '0.0.0.0:53:53'
    environment:
      TZ: "Europe/SomeWhere"
    cpus: 4
    mem_limit: 4G
    volumes:
      - ./work:/adguard/var
      - ./confdir:/adguard/etc
    networks:
      adguardhome:
        ipv4_address: 192.168.191.18
      traefik_adguard:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_adguard"
      - "traefik.http.routers.adguard.tls=true"
      - "traefik.http.routers.adguard.entrypoints=websecure"
      - "traefik.http.routers.adguard.rule=Host(`adgh.dom.tld`)"
      - "traefik.http.routers.adguard.middlewares=secHeaders@file,localIPsOnly@file,crowdsec@file,admins-auth@file"
      - "traefik.http.routers.adguard.service=adguard"
      - "traefik.http.services.adguard.loadbalancer.server.port=3000"

networks:

  adguardhome:
    name: adguardhome
    driver: macvlan
    ipam:
      config:
        - subnet: 192.168.191.16/30
          gateway: 192.168.191.17
    driver_opts:
      parent: vmbr1.104
    external: false

  traefik_adguard:
    external: true
    internal: true
    name: traefik_adguard

```
